### ISSUE TITLE
Unexpected token 

### ISSUE THREAD

**Issue by akbarazimifar** [alitnk/monopay#45]
node app.js

/home/akbar/Desktop/node taxi/node_modules/monopay/dist/drivers/saman/index.js:52
            const responseStatus = response[0]?.result?.$value;
                                               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/akbar/Desktop/node taxi/node_modules/monopay/dist/drivers.js:11:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/akbar/Desktop/node taxi/node_modules/monopay/dist/index.js:17:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

**Comment by Keivan-sf** [comment]
Can you provide the version of node you are using?
This can be a typical issue with optional chaining (`?.` operator) which is not supported in node < 14 I think
